### ISSUE TITLE
[BUG] workflow does not init submodules

### ISSUE THREAD

**Issue by davidliyutong** [mvig-robotflow/azure-kinect-apiserver#1]
should enable submodules like this:

```yaml
steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
```
